import React, { useState } from 'react';
import { QRGenerator } from '../features/qr/QRGenerator';
import { SEOHead } from '../components/SEOHead';
import { AdSensePlaceholder } from '../components/AdSensePlaceholder';
import { useRouter } from '../utils/router';
import {
  Sparkles,
  Zap,
  Palette,
  ShieldCheck,
  UserX,
  CreditCard,
  ChevronDown,
  ArrowRight,
  Layers,
} from 'lucide-react';

export const HomePage: React.FC = () => {
  const { navigate } = useRouter();
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);

  const scrollToGenerator = () => {
    const el = document.getElementById('qr-generator-section');
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const faqItems = [
    {
      q: 'What is a QR code?',
      a: 'A Quick Response (QR) code is a two-dimensional barcode capable of storing hundreds of characters of data. Modern smartphones can instantly scan QR codes with their native camera app to open websites, join Wi-Fi networks, compose emails, and more.',
    },
    {
      q: 'Is QRCodeGenix completely free?',
      a: 'Yes, QRCodeGenix is 100% free to use. There are no paywalls, hidden subscription tiers, or restricted downloads.',
    },
    {
      q: 'Do I need an account or registration to create QR codes?',
      a: 'No account, email, or registration is required. You can start creating, customizing, and downloading QR codes instantly.',
    },
    {
      q: 'Are my QR codes stored on your servers?',
      a: 'No. All QR codes are generated directly inside your web browser using client-side JavaScript and Canvas APIs. Your content stays on your device and is never uploaded to any remote database.',
    },
    {
      q: 'Can I add a custom logo or image to my QR code?',
      a: 'Yes! You can upload any PNG, JPG, or SVG logo. QRCodeGenix automatically recommends High (H) error correction and creates a background shield to ensure your QR code remains easily scannable.',
    },
    {
      q: 'Can I download QR codes in vector SVG format?',
      a: 'Yes, you can download clean, scalable vector SVG files perfect for professional printing, large banners, and high-resolution marketing assets, as well as high-res PNG files.',
    },
    {
      q: 'How does a Wi-Fi QR code work?',
      a: 'When guests scan a Wi-Fi QR code generated by QRCodeGenix, their phone recognizes the SSID, encryption type, and password, prompting them to connect with a single tap without manually typing passwords.',
    },
    {
      q: 'Can I create a WhatsApp chat QR code?',
      a: 'Yes, simply enter your phone number with your international country code and an optional pre-filled message. Scanning the code opens WhatsApp with a chat ready to send.',
    },
    {
      q: 'Can I use the generated QR codes for commercial projects?',
      a: 'Yes. All QR codes you create on QRCodeGenix can be used freely for both personal and commercial purposes, including business cards, product packaging, menus, and billboards.',
    },
    {
      q: 'What is the difference between static and dynamic QR codes?',
      a: 'Static QR codes (like those created on QRCodeGenix) encode your exact data directly into the pixel pattern. They never expire and work forever without depending on an external server or redirect service. Dynamic QR codes route through a short-URL server to allow editing the target link later.',
    },
  ];

  const websiteSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'QRCodeGenix',
    url: 'https://qrcodegenix.com',
    description: 'Free online QR Code generator to create, customize, and download high-resolution QR codes locally in your browser.',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'All',
    offers: {
      '@type': 'Offer',
      price: '0.00',
      priceCurrency: 'USD',
    },
  };

  return (
    <div className="page-wrapper home-page">
      <SEOHead
        title="Free QR Code Generator – Create Custom QR Codes Online | QRCodeGenix"
        description="Create free QR codes online for URLs, WiFi, WhatsApp, email, contact, phone and more. Customize colors, add logos, and download high-quality QR codes instantly."
        canonicalPath="/"
        schema={websiteSchema}
      />

      {/* Top Banner Ad Container */}
      <AdSensePlaceholder slot="top-banner" className="hero-top-ad" />

      {/* Hero Section */}
      <section className="hero-section" aria-labelledby="hero-title">
        <div className="hero-content">
          <div className="hero-badge">
            <span className="badge-dot" />
            <span>Free • No Sign Up • Browser-Based</span>
          </div>

          <h1 id="hero-title" className="hero-headline">
            Create QR Codes <span className="text-gradient">in Seconds</span>
          </h1>

          <p className="hero-subheadline">
            Generate, customize, and download beautiful high-quality QR codes for websites, WiFi, WhatsApp, email, and phone. Crisp vector SVGs and high-res PNGs rendered directly in your browser.
          </p>

          <div className="hero-actions">
            <button className="btn btn-primary btn-lg" onClick={scrollToGenerator}>
              <Sparkles size={18} />
              <span>Create QR Code</span>
            </button>
            <button className="btn btn-outline btn-lg" onClick={() => navigate('/qr-tools')}>
              <Layers size={18} />
              <span>Explore QR Tools</span>
            </button>
          </div>

          <p className="hero-trust-note">
            <ShieldCheck size={16} className="text-success inline-icon" /> Generated locally in your browser. Your data stays private.
          </p>
        </div>
      </section>

      {/* Main QR Code Generator */}
      <div className="generator-anchor-container">
        <QRGenerator
          heading="Create Your Custom QR Code"
          subheading="Choose a QR type, enter your content, and style your code with colors, logos, and high-res export options."
        />
      </div>

      {/* Mid Content Ad Slot */}
      <AdSensePlaceholder slot="bottom-banner" className="mid-page-ad" />

      {/* Value Pillars Section */}
      <section className="features-section" aria-labelledby="features-heading">
        <div className="section-head text-center">
          <span className="section-eyebrow">Features & Capabilities</span>
          <h2 id="features-heading" className="section-main-title">
            Everything You Need to Create Better QR Codes
          </h2>
          <p className="section-subtitle">
            Engineered for precision, security, and effortless customization.
          </p>
        </div>

        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon-box">
              <Zap size={22} className="text-primary" />
            </div>
            <h3 className="feature-title">Blazing Fast</h3>
            <p className="feature-desc">
              Generate QR codes instantly in your browser with real-time live preview as you type.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-box">
              <Palette size={22} className="text-primary" />
            </div>
            <h3 className="feature-title">Customizable</h3>
            <p className="feature-desc">
              Choose tailored color palettes, transparent backgrounds, custom sizes, and upload your brand logo.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-box">
              <Sparkles size={22} className="text-primary" />
            </div>
            <h3 className="feature-title">High Quality</h3>
            <p className="feature-desc">
              Download clean scalable SVG vectors and high-resolution PNGs up to 2048px for digital and print.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-box">
              <ShieldCheck size={22} className="text-success" />
            </div>
            <h3 className="feature-title">Privacy Friendly</h3>
            <p className="feature-desc">
              All rendering happens locally via client-side APIs. Your confidential data never leaves your device.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-box">
              <UserX size={22} className="text-primary" />
            </div>
            <h3 className="feature-title">No Sign Up</h3>
            <p className="feature-desc">
              Zero registration or account creation needed. Start creating and downloading right away.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-box">
              <CreditCard size={22} className="text-primary" />
            </div>
            <h3 className="feature-title">100% Free</h3>
            <p className="feature-desc">
              Create unlimited static QR codes without hidden fees, watermarks, or subscription paywalls.
            </p>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="steps-section" aria-labelledby="how-it-works-title">
        <div className="section-head text-center">
          <span className="section-eyebrow">Simplicity by Design</span>
          <h2 id="how-it-works-title" className="section-main-title">
            How to Create a QR Code in 3 Steps
          </h2>
        </div>

        <div className="steps-grid">
          <div className="step-card">
            <span className="step-num">01</span>
            <h3 className="step-title">Select Your QR Type</h3>
            <p className="step-text">
              Choose from website URLs, plain text, Wi-Fi login credentials, WhatsApp chats, email, or telephone numbers.
            </p>
          </div>

          <div className="step-card">
            <span className="step-num">02</span>
            <h3 className="step-title">Style & Brand</h3>
            <p className="step-text">
              Personalize foreground and background colors, verify contrast ratio, and optionally embed your brand logo.
            </p>
          </div>

          <div className="step-card">
            <span className="step-num">03</span>
            <h3 className="step-title">Download & Print</h3>
            <p className="step-text">
              Export in scalable vector SVG for print production or sharp PNG for digital use. No watermarks attached.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="faq-section" aria-labelledby="faq-title">
        <div className="section-head text-center">
          <span className="section-eyebrow">Frequently Asked Questions</span>
          <h2 id="faq-title" className="section-main-title">
            Everything You Need to Know About QRCodeGenix
          </h2>
        </div>

        <div className="faq-accordion">
          {faqItems.map((item, index) => {
            const isOpen = openFaqIndex === index;
            return (
              <div key={index} className={`faq-item ${isOpen ? 'open' : ''}`}>
                <button
                  className="faq-question-btn"
                  onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                  aria-expanded={isOpen}
                >
                  <span className="faq-question-text">{item.q}</span>
                  <ChevronDown size={18} className={`faq-chevron ${isOpen ? 'rotate' : ''}`} />
                </button>
                {isOpen && (
                  <div className="faq-answer">
                    <p>{item.a}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="cta-banner">
        <div className="cta-banner-content">
          <h2 className="cta-heading">Ready to Generate Your QR Code?</h2>
          <p className="cta-sub">
            Free forever. Instant browser-based rendering. No watermark.
          </p>
          <button className="btn btn-primary btn-lg mt-3" onClick={scrollToGenerator}>
            <span>Get Started Now</span>
            <ArrowRight size={18} />
          </button>
        </div>
      </section>
    </div>
  );
};
